### PR TITLE
Provide an easy way to install tfcmt via GitHub Actions

### PR DESCRIPTION
**Pull request by ebi-yade**
Thanks for your enthusiastic devotion into the development of such an excellent project!

I think it will be further more friendly to GitHub users with a feature like this, although I suppose that you, at least for work, use AWS CodeBuild as the platform to run Terraform on.

### CODE REVIEW

**Comment by ebi-yade** [comment]
OMG I found that the installation script does not work when the version if specified.  Please let me modify it 🙏🏽

**Comment by suzuki-shunsuke** [comment]
Thank you for your contribution.

I understand your proposal, but we would like to avoid maintaining GitHub Actions.

If we develop GitHub Actions, we would create a repository of GitHub Actions in terms of versioning.

We recommend aqua, which is Declarative CLI Version Manager written in Go.

* https://aquaproj.github.io/
* Demo: https://asciinema.org/a/457021?autoplay=1

You can install tfcmt with aqua easily and update tfcmt continuously with [Renovate](https://docs.renovatebot.com/).

aqua.yaml

```console
$ aqua init
$ aqua g >> aqua.yaml # select tfcmt
```

```yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v0.12.1 # renovate: depName=aquaproj/aqua-registry

packages:
- name: suzuki-shunsuke/tfcmt@v3.0.0
```

GitHub Actions

```yaml
      - uses: int128/aqua-action@v1
        with:
          version: v0.8.7 # renovate: depName=aquaproj/aqua
```

renovate.json

```json
{
  "extends": [
    "config:base",
    "github>aquaproj/aqua-renovate-config"
  ],
  "regexManagers": [
    {
      "fileMatch": ["^\\.github/.*\\.ya?ml$"],
      "matchStrings": [
        "version: (?<currentValue>.*?) # renovate: depName=(?<depName>.*)"
      ],
      "datasourceTemplate": "github-releases"
    }
  ]
}
```

**Comment by ebi-yade** [comment]
Hi Shunsuke,

Thank you for quick response!
It is a little bit sad that my proposal was not for your policy, but I got it.
And I'm gonna try the way you recommended when I have time to spare 🕐 

Best,

**Comment by suzuki-shunsuke** [comment]
https://github.com/suzuki-shunsuke/tfcmt/pull/160#issuecomment-1001337096

Updated the procedure.
You can introduce aqua a little more simply.

## AS IS

GitHub Actions

```yaml
      - uses: int128/aqua-action@v1
        with:
          version: v0.8.7 # renovate: depName=aquaproj/aqua
```

renovate.json

```json
{
  "extends": [
    "config:base",
    "github>aquaproj/aqua-renovate-config"
  ],
  "regexManagers": [
    {
      "fileMatch": ["^\\.github/.*\\.ya?ml$"],
      "matchStrings": [
        "version: (?<currentValue>.*?) # renovate: depName=(?<depName>.*)"
      ],
      "datasourceTemplate": "github-releases"
    }
  ]
}
```

## TO BE

GitHub Actions: https://github.com/aquaproj/aqua-installer

```yaml
- uses: aquaproj/aqua-installer@v0.4.0
  with:
    aqua_version: v0.8.7
```

renovate.json

```json
{
  "extends": [
    "config:base",
    "github>aquaproj/aqua-renovate-config#0.1.2"
  ]
}
```

**Pull request closed without merging**
